---
kind: pipeline
type: docker
name: amd64


steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  - dapper e2e-test
  volumes:
  - name: docker
    path: /var/run

volumes:
  - name: docker
    temp: {}
